# Generated by Django 3.1.2 on 2021-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'AddProduct',
            },
        ),
    ]
